from app.ai.prompts.resume_analysis import RESUME_ANALYSIS_SYSTEM_PROMPT, RESUME_ANALYSIS_USER_PROMPT
from app.ai.prompts.job_analysis import JOB_ANALYSIS_SYSTEM_PROMPT, JOB_ANALYSIS_USER_PROMPT
from app.ai.prompts.matching import MATCHING_SYSTEM_PROMPT, MATCHING_USER_PROMPT
from app.ai.prompts.resume_tailoring import RESUME_TAILORING_SYSTEM_PROMPT, RESUME_TAILORING_USER_PROMPT
from app.ai.prompts.cover_letter import COVER_LETTER_SYSTEM_PROMPT, COVER_LETTER_USER_PROMPT

__all__ = [
    "RESUME_ANALYSIS_SYSTEM_PROMPT",
    "RESUME_ANALYSIS_USER_PROMPT",
    "JOB_ANALYSIS_SYSTEM_PROMPT",
    "JOB_ANALYSIS_USER_PROMPT",
    "MATCHING_SYSTEM_PROMPT",
    "MATCHING_USER_PROMPT",
    "RESUME_TAILORING_SYSTEM_PROMPT",
    "RESUME_TAILORING_USER_PROMPT",
    "COVER_LETTER_SYSTEM_PROMPT",
    "COVER_LETTER_USER_PROMPT",
]
